### ISSUE TITLE
`Set_Enable` and `Set_Disable` functions have swapped functionality right now

### ISSUE THREAD

**Issue by nitram147** [budryerson/TFLuna-I2C#3]
`Set_Enable` and `Set_Disable` functions's definitions should be swapped.
When I wanted to turn off TF-Luna's light I had to use `Set_Enable` function instead of `Set_Disable` function. Same goes for the case when I wanted to turn it back on ( I had to use `Set_Disable` function instead of `Set_Enable`).

**Comment by budryerson** [comment]
Uh oh.  I followed the manufacturer's instruction set, but I did not test it those commands.  I will try to do so tomorrow.  If I get the same results, I will issue a new release of the library (0.2.0) this weekend.  I will also try to contact the manufacturer.  Thank you very much for your feedback.

**Comment by nitram147** [comment]
You are right that you made it based on the product datasheet (I had
checked the TF-Luna's datasheet yesterday before opening this issue).
However when I tested it on the real device it worked opposite way compared
to datasheet's description, so I assumed there has to be an error in the
datasheet description - at least my device works in the opposite way.

Dňa st 11. 8. 2021, 22:50 Bud Ryerson ***@***.***> napísal(a):

**Comment by nitram147** [comment]
You are right that you made it based on the product datasheet (I had
checked the TF-Luna's datasheet yesterday before opening this issue).
However when I tested it on the real device it worked opposite way compared
to datasheet's description, so I assumed there has to be an error in the
datasheet description - at least my device works in the opposite way.

**Comment by budryerson** [comment]
In the latest TFLuna Product Manual (v.5) the definition of I2C register 0x25 is changed:
0x00 = LiDAR off
0x01 = LiDAR on

I attached the zip file they sent me with the new Product Manual and new firmware.
(As always: **Install new firmware at your own risk**.)
I will change the library's Enable/Disable commands and release a new version this Sunday.

Thank you for your help,
Bud Ryerson
San Francisco
[tf-luna_std_v3-3-0-main-bin_2021-08-13_1128.zip](https://github.com/budryerson/TFLuna-I2C/files/6984045/tf-luna_std_v3-3-0-main-bin_2021-08-13_1128.zip)
