### ISSUE TITLE
uart version

### ISSUE THREAD

**Issue by ozgur-as** [budryerson/TFLuna-I2C#9]
hello!

thanks for the awesome libraries for tfmini products :)

will you be releasing the uart version for tfluna as well?

thanks!

**Comment by budryerson** [comment]
In serial (UART) mode, the **TFLuna** is largely compatible with the **TFMini-Plus** and is therefore able to use that library.

**Comment by ozgur-as** [comment]
i have tried tfmini-plus library for luna in serial mode and it worked.

you might change the about part and readme for tfmini-plus to reflect that it works for luna as well.

thanks!
